// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngadzshmjshfbyczuuib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nYWR6c2htanNoZmJ5Y3p1dWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzAzMDgsImV4cCI6MjA3Mzc0NjMwOH0.sficmqEMeXum4zirhN2DHKzI5SPC3ziaVKgLYWw6hSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});